### ISSUE TITLE
Cannot find name 'Thenable'.

### ISSUE THREAD

**Issue by jacobocantillo** [NativeScript/nativescript-imagepicker#32]
Hi. After updating the module tns-core-modules to 2.4.0-2016-09-21-4189 version occurs the following error in my app:

`
57 data(): Thenable<any>;

node_modules/nativescript-imagepicker/imagepicker.d.ts(57,17): error TS2304: Cannot find name 'Thenable'.

65         authorize(): Thenable<void>;
node_modules/nativescript-imagepicker/imagepicker.d.ts(65,22): error TS2304: Cannot find name 'Thenable'.

71         present(): Thenable<SelectedAsset[]>;

node_modules/nativescript-imagepicker/imagepicker.d.ts(71,20): error TS2304: Cannot find name 'Thenable'.`

**Comment by jacobocantillo** [comment]
Hi, any idea when they might release a stable version? Thank you
