### ISSUE TITLE
Imagepicker on iOS sometimes gets stuck at .present()

### ISSUE THREAD

**Issue by TsotneShonia** [NativeScript/nativescript-imagepicker#251]
### Which platform(s) does your issue occur on?
- iOS 12.1
- Emulator :  iPhone 7, iPhone X, iPhone XR - iOS 12.1
- Devices : iPhone 7 - iOS 12.1.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2
- Cross-platform modules: 5.2
- Runtime(s): 5.2 ( iOS ) (works fine on Android with 5.2)
- Plugin(s): nativescript-imagepicker is at ^6.1.0, everything else comes from tns create
- Built on : macOS Mojave 10.14.3 with XCode 10.1

### Please, tell us how to recreate the issue in as much detail as possible.
1. run `tns create` to generate a project. Generate a plain TypeScript project, with the Hello World template. The problem also occurs with Angular.
2. install the plugin with the simple `tns plugin add nativescript-imagepicker`
3. add the permission lines in the **Info.plist** file
```xml
<key>NSPhotoLibraryUsageDescription</key>
<string>Description text goes here</string>
```
4. in the **main-view-model.ts** file, add the import line :
```ts
import * as imagepicker from "nativescript-imagepicker";
```
and replace the **onTap()** function with this :
```ts
    onTap() {
        let context = imagepicker.create({mode: "single"});
        context
            .authorize()
            .then(function () {
                return context.present();
            })
            .then(function (selection) {
                console.log("selected image");
            }).catch(function (e) {
                console.log("caught : ", e);
            });
    }
```
5. run the app with a simple ```tns run ios```
6. tap the button to pop the imagepicker
7. pick an image or hit the "cancel" button if possible.

Doing steps 6 and 7 repeatedly will break the feature and make the imagepicker stuck. You can no longer pick an image (tapping it does nothing) nor can you go back. The "cancel" button gives a visual feedback on being tapped but does nothing. The user is forced to close the app.

Nothing is displayed in the console.
Sometimes, "if you're lucky", it breaks on the first attempt. Sometimes, 2nd, 4th, 5th. Sometimes it works even after picking 20 images. In those cases, restart the app on the device or emulator.
Usually it breaks around the 4th.
This also occurs in "multiple" selection mode. Images can be selected but the "done" button gets stuck instead (like the "cancel" button).

**Comment by TsotneShonia** [comment]
I've also had it occur on the sample demo provided in this repo. I just built and ran the demo, without touching any file. Tested on an iPhone 7 emulator. It worked fine initially for over 10 sequential image selection, then I closed the app (hit home button twice and slide the app up) and started it again. It immediatly broke, I couldn't pick an image nor cancel the imagepicker.

**Comment by patrikengborg** [comment]
Same problem here. I haven't noticed this problem prior to upgrading to NS 5.2.

**Comment by raphaelnm** [comment]
Same problem here on iphone 8 Plus (iOS 12.1.4)

**Comment by DickSmith** [comment]
Same problem as well after updating to {N} 5.2.

**Comment by NickIliev** [comment]
+1 reported via t-1397525.

I've reproduced the issue using [this basic demo](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/nativescript-imagepicker/t-1397525) and [the steps despised by @TsotneShonia](https://github.com/NativeScript/nativescript-imagepicker/issues/251#issue-411464812) .

On my side, it seems that the issue is reproducible on iPad with iOS 12.1.4 (I was not able to hit the issue on iPhone X, iPhone XR). The result is that hitting the  `CANCEL` is not working (but again as @TsotneShonia noticed there is the visual effect of tapping the button - its just not closing the modal)

**Comment by TsotneShonia** [comment]
Thanks everyone for confirming the issue, adding details to it, and bringing a fix.

However, I must report that the issue persists for me, despite the fix. It now behaves slightly differently.
First, I can no longer reproduce it on simulators, only on devices.
I reproduced it on both an iPhone 7 with iOS 12.1.4 and iPhone 5S with iOS 11.3.1.

The difference is that now, it can no longer break while it's being used. If it works on the first attempt, it will keep working until I close the app. But it can still "break" on the first usage. I'm testing it on this repo, with the vanilla demo.
According to my tests, there's roughly one chance out of 3 that the image picker starts broken. The symptoms look like they are the same.

**Comment by JuanDeLeon** [comment]
Same for me, using NS 5.2 and iPhone 8 with iOS 12.1.4
After updating plugin, it worked every time in simulator. 
However, for me it is breaking 100% of the times in the device.

**Comment by DimitarTodorov** [comment]
Fixed with latest release of nativecript-imagepicker@6.1.1

**Comment by JuanDeLeon** [comment]
I'm definitely still getting this on device, but less often. Trying to figure out when/why, but it's pretty random.

**Comment by TsotneShonia** [comment]
Same here, it still occurs, even with nativecript-imagepicker@6.1.1.

**Comment by darxmac** [comment]
Before updating to 6.1.1 i would get the "stuck" behaviour, but right after updating to 6.1.1 it crashes with:

```
JavaScript stack trace:
1   qb_imagePickerControllerDidFinishPickingAssets@file:///app/tns_modules/nativescript-imagepicker/imagepicker.js:103:22
2   UIApplicationMain@[native code]
3   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
4   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
5   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:185:26
6   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:103:38
7   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:87:26
8   anonymous@file:///app/main.js:10:57
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-imagepicker/imagepicker.js:103:22: JS ERROR TypeError: this._resolve is not a function. (In 'this._resolve(assets)', 'this._resolve' is undefined)

```

**Comment by darxmac** [comment]
Ok, the crash was a one-time thing, but i also get the hang when picking in 6.1.1

**Comment by DimitarTodorov** [comment]
Hello, @TsotneShonia 
We've just published 6.1.2 to npm with fix for the issue. 
Can you confirm on your side that it is fixed and reply to this thread in order to close the issue?

Regards

**Comment by TsotneShonia** [comment]
Hello, @DimitarTodorov 
I confirm it is working as expected now.
Thank you all very much.

**Comment by tingfong214** [comment]
I think the problem still occurs with version 6.2.0
with tns version 5.2.0

**Comment by b02505048** [comment]
Same here, the problem still occurs occasionally @6.2.0 ...

**Comment by Universi** [comment]
Same issue with @7.1.0

**Comment by francislow** [comment]
I ran into the same issue with imagepicker version 7.1.0 on iphone 11 emulator. It is able to run only once after restarting the application. I added a delay between authorize() and present() and it solves the issue for me.
<img width="314" alt="Screenshot 2020-12-18 at 9 40 25 PM" src="https://user-images.githubusercontent.com/42372434/102621048-ff007380-4179-11eb-9d56-a18a927a0dcb.png">
