### ISSUE TITLE
Plugin not compatible with new version of tns.

### ISSUE THREAD

**Issue by dariocamarro** [NativeScript/nativescript-imagepicker#21]
Plugin does not work with version 2.1 of tns-core . 
When will be updated the plugin?

**Comment by bradmartin** [comment]
It's working, I have a small app that I'm using and it works fine on Android.

**Comment by PanayotCankov** [comment]
@dariocamarro Could you share some details, what is not working with the plugin? Could you also try to remove and re-add the platform you are trying it on?

**Comment by adrianlaraperez88** [comment]
no working whit new update nativescript

**Comment by rrjohnson85** [comment]
@PanayotCankov While the plugin still seems to work fine for me, I've recently tried building my project with webpack and cannot get it working due to the imagepicker's outdated dependencies.  

For example, I receive the following error:

`Cannot find module "ui/styling/visual-state-constants"`

It seems that this file and potentially others were removed since version 2.0.0.

**Comment by anodal88** [comment]
I recently install this plug in and work fine for android in live sync mode, but when i compile my solution a have the fallowing error:
/home/antonio/NativeScript/xxxxx/platforms/android/src/main/java/com/tns/gen/org/nativescript/widgets/Async_CompleteCallback.java:3: error: package org.nativescript.widgets.Async does not exist
public class Async_CompleteCallback implements org.nativescript.widgets.Async.CompleteCallback {
                                                                             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileF0F1DebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileF0F1DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

My environment is Ubuntu 16.04, This error is on Android a.nd this is the version tns-android": {
      "version": "2.2.0"
    }

**Comment by anodal88** [comment]
I also have been deleted and added the android platform but i have the same error

**Comment by PanayotCankov** [comment]
We had to ship .jar since the android-upload-service had no binary upload similar to the built in iOS one and we had to build it from source. The binary support PR is now merged and we are working toward adding include.gradle with the dependency for android that should resolve similar issues.

After adding this plugin, livesync won't work in the current cli version, as the plugin requires adding native java code. You may also need to delete the platforms/android folder and you will have to `tns run android` to trigger complete build.

**Comment by adrianlaraperez88** [comment]
thanks you for you time,


these steps had already implemented for now, just waiting to see if it 
works out as it is a change in the android api leave it anchored to the 
api 22. We hope to see.

**Comment by PanayotCankov** [comment]
We are publishing new version where this should be resolved.

**Comment by adrianlaraperez88** [comment]
ok thanks 


Get Outlook for Android






On Thu, Nov 17, 2016 at 2:08 AM -0500, "Panayot Cankov" <notifications@github.com> wrote:












We are publishing new version where this should be resolved.
